# SPDX-FileCopyrightText: 2025 Felix Hilgers <contact@fhilgers.com>
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "Cargo.lock",
  "js/package.json",
  "js/package-lock.json",
  "js/.prettierrc"
]
SPDX-FileCopyrightText = "2025 Felix Hilgers <contact@fhilgers.com>"
SPDX-License-Identifier = "Apache-2.0"
