# SPDX-FileCopyrightText: 2025 Felix Hilgers <contact@fhilgers.com>
#
# SPDX-License-Identifier: Apache-2.0

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-target", "-C", "link-arg=x86_64-linux-gnu",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-target", "-C", "link-arg=aarch64-linux-gnu",
]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-target", "-C", "link-arg=aarch64-apple-darwin",
]

[target.x86_64-apple-darwin]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-target", "-C", "link-arg=x86_64-apple-darwin",
]

[target.aarch64-apple-ios]
linker = "clang"
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
  "-C", "link-arg=-target", "-C", "link-arg=aarch64-apple-ios",
]